services:
    umanit_liip_imagine_artgris_cache_resolver.resolver:
        class: Umanit\LiipImagineArtgrisCacheResolverBundle\Resolver\ArtgrisCacheResolver
        arguments:
            - "@filesystem"
            - "@router.request_context"
            - "%env(resolve:LIIP_IMAGINE_ROOT)%"
        tags:
            - { name: "liip_imagine.cache.resolver", resolver: umanit_artgris_resolver }